# Generated by Django 5.1.7 on 2025-03-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_recipe', '0002_alter_comment_id_alter_rating_id_alter_recipe_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
    ]
