# Generated by Django 5.1.7 on 2025-03-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_recipe', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
