# Generated by Django 5.1.7 on 2025-03-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_recipe', '0003_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipe'},
        ),
    ]
