# Generated by Django 5.1.7 on 2025-03-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_recipe', '0006_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
