# Generated by Django 5.1.7 on 2025-03-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_recipe', '0007_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
