name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
    test:
      uses: ./.github/workflows/test.yml

    deploy:
        runs-on: ubuntu-latest
        needs: test
        
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Deploy to PythonAnywhere
          uses: umuttopalak/pythonanywhere-deploy-action@v1.1.0
          with:
            host: 'www.pythonanywhere.com'
            username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
            api_token: ${{ secrets.PYTHONANYWHERE_TOKEN }}
            domain_name: acul4321.pythonanywhere.com